Arrumei o tester... ta chuchuzinho

diff --git a/mini-ep2/EP1/tester b/mini-ep2/EP1/tester
--- a/mini-ep2/EP1/tester
+++ b/mini-ep2/EP1/tester
@@ -1,13 +1,20 @@
-python3 ep.py $1 < $2 | sort > ./.ep_out
-if [ $? == 0 ]; then
-    sort $3 > ./.ep_exp
-    diff -q ./.ep_out ./.ep_exp
+if [[ -a $2 && -a $3 ]] && [[ $1 = "-a" || $1 = "-u" ]]; then
+    diff -q <(sort $3) <(python3 ep.py $1 < $2 | sort) &> /dev/null
     if [ $? == 0 ]; then
         echo "O teste passou com sucesso! =D"
     else
         echo "O teste falhou! =("
     fi
-    rm -f ./.ep_out ./.ep_exp
 else
-    echo "Falha ao executar o script ep.py"
+    if ! [ -a $2 ]; then
+        echo "$2 não existe"
+    fi
+    if ! [ -a $3 ]; then
+        echo "$3 não existe"
+    fi
+    if ! [[ $1 = "-a" || $1 = "-u" ]]; then
+        echo "$1: argumento invalido"
+    fi
+
+    echo "Uso: tester <-a ou -u> <arquivo de entrada> <arquivo de saida esperado>"
 fi
